drop table FILM_GENRE_MATCHES, FRIENDSHIP_REALATIONS,  FRIENDSHIP_STATUS, GENRES,
    USER_LIKES, FILMS, MPA_RATING, USERS;

CREATE TABLE IF NOT EXISTS films (
                         film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         film_name varchar(50),
                         film_description varchar(200),
                         release_date date,
                         duration int,
                         mpa int
);

CREATE TABLE IF NOT EXISTS MPA_rating (
                              MPA_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              MPA_name varchar(15)
);

CREATE TABLE IF NOT EXISTS film_genre_matches (
                                      index int PRIMARY KEY,
                                      film_id int,
                                      genre_id int
);

CREATE TABLE IF NOT EXISTS genres (
                          genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          genre_name varchar(50)
);

CREATE TABLE IF NOT EXISTS users (
                         user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         user_login varchar(50),
                         user_name varchar(50),
                         user_email varchar(50),
                         user_birthday date
);

CREATE TABLE IF NOT EXISTS friendship_realations (
                                         relation_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         first_user_id int,
                                         second_user_id int,
                                         friendship_status_id int
);

CREATE TABLE IF NOT EXISTS Friendship_status (
                                     friendship_status_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     friendship_status varchar(50)
);

CREATE TABLE IF NOT EXISTS user_likes (
                              like_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              user_id int,
                              film_id int
);

ALTER TABLE films ADD FOREIGN KEY (mpa) REFERENCES MPA_rating (MPA_id);

ALTER TABLE film_genre_matches ADD FOREIGN KEY (film_id) REFERENCES films (film_id);

ALTER TABLE film_genre_matches ADD FOREIGN KEY (genre_id) REFERENCES genres (genre_id);

ALTER TABLE friendship_realations ADD FOREIGN KEY (friendship_status_id) REFERENCES Friendship_status (friendship_status_id);

ALTER TABLE friendship_realations ADD FOREIGN KEY (first_user_id) REFERENCES users (user_id);

ALTER TABLE friendship_realations ADD FOREIGN KEY (second_user_id) REFERENCES users (user_id);

ALTER TABLE user_likes ADD FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE user_likes ADD FOREIGN KEY (film_id) REFERENCES films (film_id);

